# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_title', models.CharField(max_length=256, verbose_name='Title')),
                ('experiment_created_date', models.DateTimeField(auto_now_add=True)),
                ('experiment_start', models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 46, 34, 471159, tzinfo=utc), unique=True, verbose_name='Experiment Start Date')),
                ('experiment_projected_duration', models.DurationField(help_text='Maximum experiment duration: 4 hours.', verbose_name='Experiment Duration')),
                ('email_reminder', models.CharField(choices=[('', 'No Reminder'), ('1day', '1 Day Before'), ('1hr', '1 Hour Before'), ('30min', '30 Minutes Before'), ('15min', '15 Minutes Before'), ('atrun', 'At Runtime')], default='', help_text='The experiment will remind you when your experiment is running so you know when you can expect your results.', max_length=5, verbose_name='Email Reminder Time')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.PositiveSmallIntegerField(choices=[(1, 'Startup Command'), (2, 'One-Time Command'), (3, 'Looping Command'), (4, 'SSS One-Time Command')])),
                ('delay', models.DecimalField(decimal_places=6, max_digits=11)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SPNPGNEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.PositiveIntegerField()),
                ('spn', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('spn_length', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('pgl', models.CharField(max_length=100)),
                ('position', models.DecimalField(decimal_places=1, max_digits=2)),
                ('transmissionrate_ms', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=20)),
                ('offset', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SSSComand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.PositiveSmallIntegerField(choices=[(1, 'Startup Command'), (2, 'One-Time Command'), (3, 'Looping Command'), (4, 'SSS One-Time Command')])),
                ('parent_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.Experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoopingCommand',
            fields=[
                ('onetimecommand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='experimenteditor.OneTimeCommand')),
                ('loopdelay', models.DecimalField(decimal_places=6, max_digits=11)),
            ],
            options={
                'abstract': False,
            },
            bases=('experimenteditor.onetimecommand',),
        ),
        migrations.AddField(
            model_name='onetimecommand',
            name='parent_experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.Experiment'),
        ),
    ]
