# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='experiment_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 51, 23, 841005, tzinfo=utc), unique=True, verbose_name='Experiment Start Date'),
        ),
        migrations.AlterField(
            model_name='spnpgnentry',
            name='transmissionrate_ms',
            field=models.CharField(max_length=150),
        ),
    ]
