# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0002_auto_20170607_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='experiment_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 18, 52, 26, 579033, tzinfo=utc), unique=True, verbose_name='Experiment Start Date'),
        ),
        migrations.AlterField(
            model_name='spnpgnentry',
            name='position',
            field=models.CharField(max_length=4),
        ),
    ]
