# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0008_auto_20170608_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SPNPGNEntry',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 17, 24, 16, 251680, tzinfo=utc), unique=True, verbose_name='Experiment Start Date'),
        ),
    ]
