# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0015_auto_20170608_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSchedulingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_start', models.DateTimeField(default=datetime.datetime(2017, 6, 9, 18, 25, 27, 55592, tzinfo=utc), unique=True, verbose_name='Experiment Run Date')),
                ('experiment_projected_duration', models.DurationField(help_text='Maximum experiment duration: 4 hours.', verbose_name='Experiment Duration')),
                ('email_reminder', models.CharField(choices=[('', 'No Reminder'), ('1day', '1 Day Before'), ('1hr', '1 Hour Before'), ('30min', '30 Minutes Before'), ('15min', '15 Minutes Before'), ('atrun', 'At Runtime')], default='', help_text='We will remind you when your experiment is running so you know when you can expect your results.', max_length=5, verbose_name='Email Reminder Time')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeSSSCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.DecimalField(decimal_places=6, max_digits=11)),
                ('commandchoice', models.PositiveSmallIntegerField(choices=[(1, 'Turn Ignition On'), (0, 'Turn Ignition Off')])),
                ('duration', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='loopingcommand',
            name='onetimecommand_ptr',
        ),
        migrations.RemoveField(
            model_name='onetimecommand',
            name='parent_experiment',
        ),
        migrations.RemoveField(
            model_name='ssscomand',
            name='parent_experiment',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='email_reminder',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='experiment_projected_duration',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='experiment_start',
        ),
        migrations.AddField(
            model_name='experiment',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LoopingCommand',
        ),
        migrations.DeleteModel(
            name='OneTimeCommand',
        ),
        migrations.DeleteModel(
            name='SSSComand',
        ),
        migrations.AddField(
            model_name='onetimessscommand',
            name='parent_experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.Experiment'),
        ),
        migrations.AddField(
            model_name='experimentschedulinginfo',
            name='related_experiment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_info_for', to='experimenteditor.Experiment'),
        ),
    ]
