# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0016_auto_20170609_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimessscommand',
            name='duration',
        ),
        migrations.AddField(
            model_name='onetimessscommand',
            name='quantity',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='experimentschedulinginfo',
            name='experiment_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 12, 19, 39, 16, 205916, tzinfo=utc), unique=True, verbose_name='Experiment Run Date'),
        ),
        migrations.AlterField(
            model_name='onetimessscommand',
            name='commandchoice',
            field=models.CharField(choices=[('TurnControlUnitOn', 'Turn Control Unit On'), ('TurnControlUnitOff', 'Turn Control Unit Off')], max_length=256),
        ),
    ]
