# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0017_auto_20170612_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentschedulinginfo',
            name='experiment_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 12, 20, 18, 23, 689892, tzinfo=utc), unique=True, verbose_name='Experiment Run Date'),
        ),
        migrations.AlterField(
            model_name='onetimessscommand',
            name='commandchoice',
            field=models.CharField(choices=[('TurnIgnitionOn', 'Turn Ignition On'), ('TurnIgnitionOff', 'Turn Ignition Off')], max_length=256, verbose_name='Command Choice'),
        ),
        migrations.AlterField(
            model_name='onetimessscommand',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
