# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0018_auto_20170612_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentschedulinginfo',
            name='email_reminder',
            field=models.CharField(blank=True, choices=[('', 'No Reminder'), ('1day', '1 Day Before'), ('1hr', '1 Hour Before'), ('30min', '30 Minutes Before'), ('15min', '15 Minutes Before'), ('atrun', 'At Runtime')], default='', help_text='We will remind you when your experiment is running so you know when you can expect your results.', max_length=5, verbose_name='Email Reminder Time'),
        ),
        migrations.AlterField(
            model_name='experimentschedulinginfo',
            name='experiment_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 17, 42, 0, 535062, tzinfo=utc), unique=True, verbose_name='Experiment Run Date'),
        ),
    ]
