# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20160715_0028'),
        ('experimenteditor', '0019_auto_20170613_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentschedulinginfo',
            name='experiment_projected_duration',
        ),
        migrations.RemoveField(
            model_name='experimentschedulinginfo',
            name='experiment_start',
        ),
        migrations.AddField(
            model_name='experimentschedulinginfo',
            name='related_event',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_event_info_for', to='schedule.Event'),
        ),
        migrations.AlterField(
            model_name='experimentschedulinginfo',
            name='email_reminder',
            field=models.CharField(blank=True, choices=[('', 'No Reminder'), ('1day', '1 Day Before'), ('1hr', '1 Hour Before'), ('30min', '30 Minutes Before'), ('15min', '15 Minutes Before'), ('10min', '10 Minutes Before')], default='', help_text='We will remind you when your experiment is running so you know when you can expect your results.', max_length=5, verbose_name='Email Reminder Time'),
        ),
        migrations.AlterField(
            model_name='onetimessscommand',
            name='commandchoice',
            field=models.CharField(choices=[('TurnIgnitionOn', 'Turn Ignition On'), ('TurnIgnitionOff', 'Turn Ignition Off')], max_length=256, verbose_name='Command Type'),
        ),
        migrations.AlterField(
            model_name='onetimessscommand',
            name='delay',
            field=models.DecimalField(decimal_places=6, help_text='Enter a number, in seconds, with up to 6 decimal places. 0 is the start of the experiment.', max_digits=11, verbose_name='Command Start Time'),
        ),
    ]
