# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0020_auto_20170614_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='scheduled',
        ),
        migrations.AddField(
            model_name='experiment',
            name='exp_pk',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experimentschedulinginfo',
            name='related_event',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_event_info_for', to='schedule.Event'),
        ),
    ]
