# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0022_experiment_is_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimessscommand',
            name='is_repeated',
            field=models.BooleanField(default=False, help_text='Check this if you want to repeat this command more than once at a regular interval.', verbose_name='Enable Repetition'),
        ),
        migrations.AddField(
            model_name='onetimessscommand',
            name='repeat_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Repeat Count'),
        ),
        migrations.AddField(
            model_name='onetimessscommand',
            name='repeat_delay',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Repeat Delay'),
        ),
    ]
