# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0023_auto_20170619_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimessscommand',
            name='repeat_delay',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True, verbose_name='Repeat Delay'),
        ),
    ]
