# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import experimenteditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0024_auto_20170619_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservableQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xdata', experimenteditor.models.SeparatedValuesField()),
                ('ydata', experimenteditor.models.SeparatedValuesField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
