# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import experimenteditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0025_observablequantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observablequantity',
            name='name',
        ),
        migrations.AddField(
            model_name='observablequantity',
            name='entry',
            field=models.ManyToManyField(to='experimenteditor.SPNPGNEntry'),
        ),
        migrations.AddField(
            model_name='observablequantity',
            name='related_experiment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.Experiment'),
        ),
        migrations.AlterField(
            model_name='observablequantity',
            name='xdata',
            field=experimenteditor.models.SeparatedValuesField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='observablequantity',
            name='ydata',
            field=experimenteditor.models.SeparatedValuesField(blank=True, default=[]),
        ),
    ]
