# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0026_auto_20170620_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observablequantity',
            name='related_experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.Experiment'),
        ),
    ]
