# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0027_auto_20170620_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observablequantity',
            name='entry',
        ),
        migrations.AddField(
            model_name='observablequantity',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.SPNPGNEntry'),
        ),
    ]
