# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0028_auto_20170621_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observablequantity',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.SPNPGNEntry'),
        ),
    ]
