# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 15:26
from __future__ import unicode_literals

from django.db import migrations
import experimenteditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0029_auto_20170621_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observablequantity',
            options={'verbose_name': 'Observable Quantity', 'verbose_name_plural': 'Observable Quantities'},
        ),
        migrations.AlterField(
            model_name='observablequantity',
            name='xdata',
            field=experimenteditor.models.SeparatedValuesField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='observablequantity',
            name='ydata',
            field=experimenteditor.models.SeparatedValuesField(blank=True, default=[], null=True),
        ),
    ]
