# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0030_auto_20170621_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimessscommand',
            name='commandchoice',
            field=models.CharField(choices=[('TurnIgnitionOn', 'Turn Ignition On'), ('TurnIgnitionOff', 'Turn Ignition Off'), ('SetWheelBasedVehicleSpeed', 'Set Wheel-Based Vehicle Speed')], max_length=256, verbose_name='Command Type'),
        ),
    ]
