# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 17:39
from __future__ import unicode_literals

from django.db import migrations
import experimenteditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0032_auto_20170628_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimessscommand',
            name='quantity',
            field=experimenteditor.models.SeparatedValuesField(blank=True, default=None, null=True),
        ),
    ]
