# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0033_auto_20170629_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimessscommand',
            name='commandchoice',
            field=models.CharField(choices=[('TurnIgnitionOn', 'Turn Ignition On'), ('TurnIgnitionOff', 'Turn Ignition Off'), ('SetAxleBasedVehicleSpeed', 'Set Axle-Based Vehicle Speed (mph)'), ('SetBrakeAmount', 'Set Brake Amount (%)')], max_length=256, verbose_name='Command'),
        ),
        migrations.AlterField(
            model_name='onetimessscommand',
            name='repeat_delay',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Time, in seconds, between the consecutive executions of this command.', max_digits=11, null=True, verbose_name='Repeat Delay'),
        ),
    ]
