# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0034_auto_20170629_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimessscommand',
            name='commandchoice',
            field=models.CharField(choices=[('TurnIgnitionOn(0)', 'Turn Ignition On (none)'), ('TurnIgnitionOff(0)', 'Turn Ignition Off (none)'), ('SetAxleBasedVehicleSpeed(1)', 'Set Axle-Based Vehicle Speed (mph)'), ('SetBrakePressure(2)', 'Set Brake Pressure (0-100%,duration in s)')], max_length=256, verbose_name='Command'),
        ),
    ]
