# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0035_auto_20170629_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CANCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.DecimalField(decimal_places=6, help_text='Enter a number, in seconds, with up to 6 decimal places. 0 is the start of the experiment.', max_digits=11, verbose_name='Command Start Time')),
                ('length', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=0)),
                ('message', models.CharField(default='0000000000000000', max_length=16)),
                ('message_id', models.CharField(default='00000000', max_length=8)),
                ('interface', models.PositiveSmallIntegerField(choices=[(0, 'can0'), (1, 'can1')], default=0)),
                ('parent_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.Experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='onetimessscommand',
            name='commandchoice',
            field=models.CharField(choices=[('', '--Select Command--'), ('TurnIgnitionOn(0)', 'Turn Ignition On (none)'), ('TurnIgnitionOff(0)', 'Turn Ignition Off (none)'), ('SetAxleBasedVehicleSpeed(1)', 'Set Axle-Based Vehicle Speed (mph)'), ('SetBrakePressure(2)', 'Set Brake Pressure (0-100%, duration in s)'), ('EndExperiment(0)', 'End Experiment (none)')], max_length=256, verbose_name='Command'),
        ),
    ]
