# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0036_auto_20170712_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancommand',
            name='is_extended_can',
            field=models.BooleanField(default=False),
        ),
    ]
