# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20160715_0028'),
        ('experimenteditor', '0038_cangencommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(blank=True, default=None, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Event')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.Experiment')),
            ],
            options={
                'verbose_name': 'Experiment Run',
                'verbose_name_plural': 'Experiment Runs',
            },
        ),
        migrations.AddField(
            model_name='observablequantity',
            name='related_run',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.RunResult'),
        ),
    ]
