# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-21 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0040_auto_20170726_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECUUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.DecimalField(decimal_places=6, help_text='Enter a number, in seconds, with up to 6 decimal places. 0 is the start of the experiment.', max_digits=11, verbose_name='Command Start Time')),
                ('update_type', models.PositiveSmallIntegerField(choices=[(1, 'VIN Update'), (2, 'Governor Speed Update')], default=1)),
                ('vin', models.CharField(blank=True, default=None, max_length=21, null=True)),
                ('governor_speed', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6)),
                ('parent_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.Experiment')),
            ],
            options={
                'verbose_name': 'ECU Update',
            },
        ),
    ]
