# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0041_ecuupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecuupdate',
            name='governor_speed',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
