# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0042_auto_20180522_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observablequantity',
            name='entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='experimenteditor.SPNPGNEntry'),
        ),
    ]
