# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0044_auto_20180522_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='observablequantity',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
