# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimenteditor', '0046_auto_20180524_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='observablequantity',
            name='plottable',
            field=models.BooleanField(default=True),
        ),
    ]
